version: "3.7"

services:
  mongodb:
    image: mongo:6.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    ports:
        - "${MONGO_PORT}:${MONGO_PORT}"

  web:
    build: .
    command: web
    env_file: .env
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    depends_on:
      - worker
      - mongodb
    volumes:
        - .:/app

  redis:
    image: redis:7.0.7
    ports:
        - "${REDIS_PORT}:${REDIS_PORT}"

  worker:
    build: .
    command: worker
    env_file: .env
    depends_on:
      - redis
      - mongodb
    volumes:
      - .:/app

  tg_bot:
    build: .
    command: tg_bot
    env_file: .env
    volumes:
      - .:/app
